remove RenderModeServer attribute
github actions throws errors while building:

#15 5.637 /src/OryAdmin/Components/Pages/Identities/Create.razor(6,13): error CS0246: The type or namespace name 'RenderModeServerAttribute' could not be found (are you missing a using directive or an assembly reference?) [/src/OryAdmin/OryAdmin.csproj]